# This is a basic workflow to help you get started with Actions

name: generate animation

on:
  workflow_dispatch: # execute manually
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"


jobs:
    snake-animation:
      runs-on: ubuntu-latest
      steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: annaluzserena
          svg_out_path: dist/github-contribution-grid-snake.svg
